Fix module display_intf_headers dependency
error: hardware/qcom-caf/sdm660/display/Android.bp:18:1: "display_headers" depends on undefined module "display_intf_headers"
Module "display_headers" is defined in namespace "hardware/qcom-caf/msm8998" which can read these 2 namespaces: ["hardware/qcom-caf/msm8998" "."]
Module "display_intf_headers" can be found in these namespaces: ["hardware/qcom/display/msm8909" "hardware/qcom/sdm845" "vendor/qcom/opensource/commonsys-intf/disp
lay"]

Signed-off-by: Kneba <abenkenary3@gmail.com>